Fix URL, add aap_configuration collection (#40)

diff --git a/tools/execution_environments/ee-multicloud-public/Containerfile b/tools/execution_environments/ee-multicloud-public/Containerfile
--- a/tools/execution_environments/ee-multicloud-public/Containerfile
+++ b/tools/execution_environments/ee-multicloud-public/Containerfile
@@ -1,11 +1,10 @@
-FROM registry.access.redhat.com/ubi8/ubi
+# ----------------------------------------------------------------------------------
+# Build base image
+# ----------------------------------------------------------------------------------
+ARG EE_BASE_IMAGE="registry.access.redhat.com/ubi9/ubi"
 
-ENV DESCRIPTION="Community Chained Execution Environment for AgnosticD and Red Hat Demo Platform"
-LABEL ansible-execution-environment=true \
-      name="agnosticd/ee-multicloud" \
-      maintainer="Red Hat CoP" \
-      description="${DESCRIPTION}" \
-      summary="${DESCRIPTION}"
+# Building base
+FROM $EE_BASE_IMAGE as base
 
 USER root
 WORKDIR /root
@@ -23,39 +22,69 @@ RUN dnf install -y \
         libxml2-devel \
         openssl \
         openssl-devel \
-        python3.11 \
-        python3.11-devel \
-        python3.11-pip \
+        python3 \
+        python3-devel \
+        python3-pip \
         rsync \
         sshpass \
         tar \
         unzip \
         vim \
-        curl \
-        wget \
-    && dnf clean all
+        curl-minimal \
+        wget
+RUN dnf clean all
 
 # Python
-RUN alternatives --set python /usr/bin/python3.11 \
-    && alternatives --set python3 /usr/bin/python3.11 \
-    && alternatives --install /usr/bin/pip pip /usr/bin/pip3.11 1
 RUN pip install --no-cache-dir --upgrade pip
 COPY requirements.txt /tmp/requirements.txt
 RUN pip install --no-cache-dir -r /tmp/requirements.txt
 
-# Galaxy collections and roles
+# ----------------------------------------------------------------------------------
+# Build Galaxy image from base image
+# ----------------------------------------------------------------------------------
+FROM base as galaxy
+
+ARG AAP_CERTIFIED_TOKEN=notset
+ARG AAP_VALIDATED_TOKEN=notset
+
 COPY ansible.cfg /root/.ansible.cfg
 COPY requirements.yml /tmp/requirements.yml
-RUN ansible-galaxy role install \
-    -r /tmp/requirements.yml \
-    --roles-path "/usr/share/ansible/roles" \
-    && ansible-galaxy collection install -vv \
-    -r /tmp/requirements.yml \
-    --collections-path "/usr/share/ansible/collections" \
-    && pip install --no-cache-dir -r /usr/share/ansible/collections/ansible_collections/azure/azcollection/requirements.txt \
-    && pip install --no-cache-dir -r /usr/share/ansible/collections/ansible_collections/community/vmware/requirements.txt \
-    && pip install --no-cache-dir -r /usr/share/ansible/collections/ansible_collections/google/cloud/requirements.txt \
-    && pip install --no-cache-dir -r /usr/share/ansible/collections/ansible_collections/kubernetes/core/requirements.txt
+
+RUN echo --------------------------------------------------
+RUN echo Certified Token: ${AAP_CERTIFIED_TOKEN}
+RUN echo Validated Token: ${AAP_VALIDATED_TOKEN}
+RUN echo --------------------------------------------------
+
+# Set tokens as environment variables for ansible-galaxy to use with the configured servers
+ENV ANSIBLE_GALAXY_SERVER_CERTIFIED_TOKEN=${AAP_CERTIFIED_TOKEN}
+ENV ANSIBLE_GALAXY_SERVER_VALIDATED_TOKEN=${AAP_VALIDATED_TOKEN}
+
+RUN ansible-galaxy role install -r /tmp/requirements.yml --roles-path "/usr/share/ansible/roles"
+RUN for i in 1 2 3; do \
+      ansible-galaxy collection install -vv -r /tmp/requirements.yml --collections-path "/usr/share/ansible/collections" && break || \
+      { echo "Attempt $i failed. Retrying in 5 seconds..."; sleep 5; }; \
+    done && \
+    ansible-galaxy collection list --collections-path "/usr/share/ansible/collections" || \
+    { echo "Failed to install collections after 3 attempts"; exit 1; }
+
+
+# ----------------------------------------------------------------------------------
+# Build Execution Environment image from base & galaxy images
+# ----------------------------------------------------------------------------------
+FROM base as final
+
+ENV DESCRIPTION="Community Chained Execution Environment for AgnosticD and Red Hat Demo Platform"
+LABEL ansible-execution-environment=true \
+      name="agnosticd/ee-multicloud" \
+      maintainer="Red Hat CoP" \
+      description="${DESCRIPTION}" \
+      summary="${DESCRIPTION}"
+
+COPY --from=galaxy /usr/share/ansible /usr/share/ansible
+RUN pip install --no-cache-dir -r /usr/share/ansible/collections/ansible_collections/azure/azcollection/requirements.txt
+RUN pip install --no-cache-dir -r /usr/share/ansible/collections/ansible_collections/community/vmware/requirements.txt
+RUN pip install --no-cache-dir -r /usr/share/ansible/collections/ansible_collections/google/cloud/requirements.txt
+RUN pip install --no-cache-dir -r /usr/share/ansible/collections/ansible_collections/kubernetes/core/requirements.txt
 
 # AWS, Bitwarden, OC client
 COPY install_binaries.sh /tmp/install_binaries.sh
@@ -63,7 +92,7 @@ RUN /tmp/install_binaries.sh
 
 # Azure CLI
 RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc \
-    && dnf install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm \
+    && dnf install -y https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm \
     && dnf install -y azure-cli \
     && dnf clean all
 
